---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: upload ssl certificate
  template:
    src: filebeat.crt.j2
    dest: /etc/filebeat/forwarder.crt
  when: filebeat_ssl_certificate is defined

- name: ensure filebeat conf.d folder exists
  file: >
    path={{ filebeat_confd_dir }}
    state=directory
  when: filebeat_confd_dir is defined

- name: create filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  tags:
    - filebeat_config
  notify:
    - restart filebeat

- name: ensure monit conf folder exists
  file: >
    path={{ filebeat_monit_config | dirname }}
    state=directory
  when: filebeat_monit_config is defined

- name: place filebeat monit config
  template:
    src: monit.filebeat.conf.j2
    dest: "{{ filebeat_monit_config }}"
  when: filebeat_monit_config is defined
  notify:
    - reload monit

- name: flush handlers to prevent start then restart
  meta: flush_handlers

- name: start and enable filebeat
  service:
    name: filebeat
    state: started
    enabled: true
  ignore_errors: yes
