---
- name: Stop and deactivate ansible filebeat service
  service:
    name: filebeat
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Stop and deactivate ansible filebeat monit
  shell: monit stop filebeat && monit unmonitor filebeat
  ignore_errors: yes

- name: Remove monit config
  file: path=/etc/monit/conf.d/filebeat.conf state=absent
  ignore_errors: yes
  notify:
   - reload monit

- name: Remove filebeat configs
  command: rm -f /etc/filebeat/conf.d/*
  ignore_errors: yes

- name: Reset filebeat register
  file: path={{ item }} state=absent
  with_items:
    - "/.filebeat"
    - "/root/.filebeat"
  when: filebeat_remove_register is defined

