---
- name: restart filebeat
  service:
    name: filebeat
    state: restarted

- name: reload monit
  service:
    name: monit
    state: reloaded
  ignore_errors: yes

- name: reload filebeat
  service:
    name: filebeat
    state: restarted
  ignore_errors: yes
